import React from 'react';
import styled from 'styled-components';
import {
  Container,
  Grid,
  Header,
  Icon,
  Message,
  Button,
} from 'semantic-ui-react';
import { connect } from 'react-redux';

import DodoTable from 'components/DodoTable';
import {
  fetchAllCompanies,
  toggleRobotEdit,
  fetchAllRobots,
  addNewRobot,
} from 'actions';
import { robotRedux, companyRedux } from 'constants/propTypes';
import { ERROR, LOADING } from 'constants/misc';

const StyleWrapper = styled(Container)``;

class RobotsPage extends React.Component {
  static propTypes = {
    robot: robotRedux,
    company: companyRedux,
  };
  state = {
    adding: false,
  };

  componentDidMount() {
    this.props.fetchAllCompanies();
    this.props.fetchAllRobots();
  }

  toggleAdding = () => {
    this.setState({ adding: !this.state.adding });
  };

  add = robot => {
    this.props.addNewRobot(robot);
    this.toggleAdding();
  };
  edit = () => {};

  render() {
    const fields = [
      {
        key: '_id',
        editor: ({ innerRef, ...props }) => (
          <input
            ref={innerRef}
            {...props}
            disabled
            placeholder="Robot ID will be autogenerated"
          />
        ),
        display: ({ value }) => <p>{value}</p>,
      },
      {
        key: 'leaser_id',
        editor: ({ innerRef, ...props }) => (
          <select className="ui fluid dropdown" ref={innerRef} {...props}>
            {this.props.company.value.map(({ _id, name }) => (
              <option value={_id} key={_id}>
                {name}
              </option>
            ))}
          </select>
        ),
        display: ({ value }) => (
          <p>
            {value &&
              this.props.company.value.find(({ _id }) => _id === value).name}
          </p>
        ),
      },
      {
        key: 'model',
        editor: ({ innerRef, ...props }) => (
          <select className="ui fluid dropdown" ref={innerRef} {...props}>
            <option value="V1">V1</option>
          </select>
        ),
        display: ({ value }) => <p>{value}</p>,
      },
    ];

    return (
      <StyleWrapper fluid>
        <Grid columns="equal">
          <Grid.Row centered>
            <Header as="h2" icon textAlign="center">
              <Icon name="truck" circular />
              <Header.Content>Robots</Header.Content>
            </Header>
          </Grid.Row>
          {this.props.company.status === ERROR ||
            (this.props.robot.status === ERROR &&
              this.state.showErr && (
                <Grid.Row centered>
                  <Message negative>
                    <p>
                      <strong>Error!</strong>{' '}
                      {this.props.user.status === ERROR
                        ? this.props.user.error
                        : this.props.company.error}
                    </p>
                  </Message>
                </Grid.Row>
              ))}
          <Grid.Row centered>
            <DodoTable
              loading={
                this.props.robot.status === LOADING ||
                this.props.robot.status === LOADING
              }
              fields={fields}
              headers={{ _id: 'ID', leaser_id: 'Leaser', model: 'Model' }}
              rows={this.props.robot.value}
              toggleEdit={this.props.toggleRobotEdit}
              adding={this.state.adding}
              defaultAddValue={{
                _id: '',
                leaser_id: '',
                model: '',
                editing: true,
              }}
              addFunc={this.add}
              toggleAdd={this.toggleAdding}
              addButton={() => (
                <Button
                  floated="right"
                  icon
                  labelPosition="left"
                  positive
                  size="small"
                  onClick={this.toggleAdding}
                >
                  <Icon name="truck" /> Add Robot
                </Button>
              )}
              editFunc={this.edit}
              deleteFunc={() => {}}
            />
          </Grid.Row>
        </Grid>
      </StyleWrapper>
    );
  }
}

export default connect(
  ({ company, robot }) => ({ company, robot }),
  { fetchAllCompanies, toggleRobotEdit, fetchAllRobots, addNewRobot },
)(RobotsPage);
